package pelemenguin.classjs.content;

import java.util.ArrayList;

import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import dev.latvian.mods.kubejs.typings.Info;
import pelemenguin.util.DescriptorUtils;

public class MethodCreator {

    private ClassCreator parent;

    private int access = 0;
    private String name;
    private String descriptor;

    // Parameter names used in MethodCodeBuilder
    private String[] paramNames;
    
    public MethodCreator(ClassCreator parent, String name, String[] parameterTypes, String returnType) {
        this.parent = parent;
        this.name = name;
        this.descriptor = DescriptorUtils.toMethodDescriptor(parameterTypes, returnType);
    }

    @Info(
        """
        Remove `public`, `private`, and `protected` modifiers from this method.
        Such a method can only be accessed from classes in the same package.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toDefault() {
        this.access &= ~(Opcodes.ACC_PUBLIC | Opcodes.ACC_PRIVATE | Opcodes.ACC_PROTECTED);
        return this;
    }

    @Info(
        """
        Set the method to `public`.
        A *public* method can be accessed from any other class.

        **Note:** Interface methods *must* set this flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toPublic() {
        this.toDefault();
        this.access |= Opcodes.ACC_PUBLIC;
        return this;
    }

    @Info(
        """
        Set the method to `private`.
        A *private* method can only be accessed from within the same class.

        **Note:** This flag *cannot* be set together with `abstract` flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toPrivate() {
        this.toDefault();
        this.access |= Opcodes.ACC_PRIVATE;
        return this;
    }

    @Info(
        """
        Set the method to `protected`.
        A *protected* method can be accessed from classes in the same package and subclasses.

        **Note:** Interface methods *cannot* set this flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toProtected() {
        this.toDefault();
        this.access |= Opcodes.ACC_PROTECTED;
        return this;
    }

    @Info(
        """
        Set the method to `static`.
        A *static* method belongs to the class rather than an instance of the class.

        **Note:** This flag *cannot* be set together with `abstract` flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toStatic() {
        this.access |= Opcodes.ACC_STATIC;
        return this;
    }

    @Info(
        """
        Remove the `static` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notStatic() {
        this.access &= ~Opcodes.ACC_STATIC;
        return this;
    }

    @Info(
        """
        Set the method to `final`.
        A *final* method cannot be overridden by subclasses.

        **Note:** Interface methods *cannot* set this flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toFinal() {
        this.access |= Opcodes.ACC_FINAL;
        return this;
    }

    @Info(
        """
        Remove the `final` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notFinal() {
        this.access &= ~Opcodes.ACC_FINAL;
        return this;
    }

    @Info(
        """
        Set the method to `synchronized`.
        A *synchronized* method can only be accessed by one thread at a time.

        **Note:** Interface methods *cannot* set this flag.
            This flag *cannot* be set together with `abstract` flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toSynchronized() {
        this.access |= Opcodes.ACC_SYNCHRONIZED;
        return this;
    }

    @Info(
        """
        Remove the `synchronized` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notSynchronized() {
        this.access &= ~Opcodes.ACC_SYNCHRONIZED;
        return this;
    }

    @Info(
        """
        Set the method to be a `bridge` method.
        A *bridge* method is a synthetic method that is generated by the compiler to handle type erasure in generics.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toBridge() {
        this.access |= Opcodes.ACC_BRIDGE;
        return this;
    }

    @Info(
        """
        Remove the `bridge` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notBridge() {
        this.access &= ~Opcodes.ACC_BRIDGE;
        return this;
    }

    @Info(
        """
        Set the method to be a `varargs` method.
        A *varargs* method can accept a variable number of arguments.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toVarargs() {
        this.access |= Opcodes.ACC_VARARGS;
        return this;
    }

    @Info(
        """
        Remove the `varargs` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notVarargs() {
        this.access &= ~Opcodes.ACC_VARARGS;
        return this;
    }

    @Info(
        """
        @deprecated You cannot actually creates a `native` method as it requires native code implementation.

        Set the method to be a `native` method.
        A *native* method is implemented in native code using JNI.

        **Note:** Interface methods *cannot* set this flag.
            This flag *cannot* be set together with `abstract` flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toNative() {
        this.access |= Opcodes.ACC_NATIVE;
        return this;
    }

    @Info(
        """
        @deprecated You cannot actually creates a `native` method as it requires native code implementation.

        Remove the `native` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notNative() {
        this.access &= ~Opcodes.ACC_NATIVE;
        return this;
    }

    @Info(
        """
        Set the method to be an `abstract` method.
        An *abstract* method is a method that is declared without an implementation.

        **Note:** Interface methods *must* set this flag.
            This flag *cannot* be set together with `private`, `static`, `final`, `synchronized`, or `native` flags.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toAbstract() {
        this.access |= Opcodes.ACC_ABSTRACT;
        return this;
    }

    @Info(
        """
        Remove the `abstract` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notAbstract() {
        this.access &= ~Opcodes.ACC_ABSTRACT;
        return this;
    }

    @Info(
        """
        @deprecated This flag is unused in class file version 61 (Java 17) or above.

        Set the method to be a `strictfp` method.
        A *strictfp* method is a method that adheres to strict floating-point calculations.

        **Note:** This flag *cannot* be set together with `abstract` flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toStrictfp() {
        this.access |= Opcodes.ACC_STRICT;
        return this;
    }

    @Info(
        """
        @deprecated This flag is unused in class file version 61 (Java 17) or above.

        Remove the `strictfp` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notStrictfp() {
        this.access &= ~Opcodes.ACC_STRICT;
        return this;
    }

    @Info(
        """
        Set the method to be a `synthetic` method.
        A *synthetic* method is a method that is generated by the compiler and does not appear in the source code.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toSynthetic() {
        this.access |= Opcodes.ACC_SYNTHETIC;
        return this;
    }

    @Info(
        """
        Remove the `synthetic` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notSynthetic() {
        this.access &= ~Opcodes.ACC_SYNTHETIC;
        return this;
    }

    @Info(
        """
        Specify the parameter names to use later in `ByteCodeBuilder`.

        By default, `arg0`, `arg1`, etc. are used to refer to method parameters.

        @param paramNames - The name of parameters. Must have the same length as the parameter types specified when creating this method.
        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator parameterNames(String[] paramNames) {
        this.paramNames = paramNames;
        return this;
    }

    @Info(
        """
        Begin byte code building.

        If you want to create *abstract* methods, use {@linkcode noCode}.

        @returns A `MethodCodeBuilder` for byte code building.  

        **Note:** After the `build()` method of the `MethodCodeBuilder` is called,
        The parent `ClassCreator` is returned directly.
        That means, once you have called this `code()` method, you should no longer access this `MethodCreator` again.
        Access modifier and other properties of this method should be set before calling this method.
        """
    )
    public MethodCodeBuilder code() {
        return new MethodCodeBuilder(this);
    }

    @Info(
        """
        Create a method without any code.
        This is used when creating abstract methods.

        **Note:** After calling this method, the parent `ClassCreator` is returned directly.
            That means, once you have called this `noCode()` method, you should no longer access this `MethodCreator` again.
            Access modifier and other properties of this method should be set before calling this method.

        @returns The parent `ClassCreator`.
        """
    )
    public ClassCreator noCode() {
        MethodVisitor mv = this.parent.classWriter.visitMethod(this.access, this.name, this.descriptor, null, null);
        mv.visitEnd();
        return this.parent;
    }

    public static class MethodCodeBuilder {

        private MethodCreator parent;

        private MethodVisitor methodVisitor;

        private ArrayList<String> localVariableNames = new ArrayList<>();
        
        // true for long variables, false for short variables
        private ArrayList<Boolean> localVariableTypes = new ArrayList<>();

        public MethodCodeBuilder(MethodCreator parent) {
            this.parent = parent;
            this.methodVisitor = this.parent.parent.classWriter.visitMethod(this.parent.access, this.parent.name, this.parent.descriptor, null, null);
            this.methodVisitor.visitCode();

            String[] paramTypes = DescriptorUtils.fromMethodDescriptor(this.parent.descriptor);
            if ((this.parent.access & Opcodes.ACC_STATIC) == 0) {
                this.localVariableNames.add("this");
                this.localVariableTypes.add(false);
            }

            String[] tempVarNames = this.parent.paramNames;
            if (tempVarNames == null) {
                tempVarNames = new String[paramTypes.length - 1];
                for (int i = 0; i < paramTypes.length - 1; i ++) {
                    tempVarNames[i] = "arg" + i;
                }
            } else if (tempVarNames.length != paramTypes.length - 1) {
                throw new IllegalArgumentException("Parameter names count does not match parameter types count");
            }

            for (int i = 0; i < paramTypes.length - 1; i ++) {
                boolean type = switch (paramTypes[i]) {
                    case "long", "double" -> true;
                    default -> false;
                };
                String name = tempVarNames[i];
                this.localVariableNames.add(name);
                this.localVariableTypes.add(type);
                if (type) {
                    this.localVariableNames.add(null);
                    this.localVariableTypes.add(null);
                }
            }
        }

        @Info(
            """
            Add a `nop` (no operation) instruction to the method.

            The `nop` instruction does nothing and is often used for alignment or timing purposes.

            **Operand Stack:**

            {...} → {...}

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder noOperation() {
            this.methodVisitor.visitInsn(Opcodes.NOP);
            return this;
        }

        @Info(
            """
            Add a `aconst_null` instruction to the method.

            The `aconst_null` instruction pushes a `null` reference onto the operand stack.

            **Operand Stack:**

            { ... } → { ... , `null` }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pushNull() {
            this.methodVisitor.visitInsn(Opcodes.ACONST_NULL);
            return this;
        }

        @Info(
            """
            Add an instruction to push an integer constant onto the operand stack.

            The method optimizes the instruction based on the value of the integer:
            - For values between -1 and 5 (inclusive), it uses the `iconst_<i>` instructions.
            - For values between -128 and 127 (inclusive), it uses the `bipush` instruction.
            - For values between -32,768 and 32,767 (inclusive), it uses the `sipush` instruction.
            - For all other values, it uses the `ldc` instruction.

            **Operand Stack:** (*i* is the pushed integer constant.)

            { ... } → { ... , *i* }

            @param i - The integer constant to push onto the operand stack.
            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pushInt(int i) {
            if (i >= -1 && i <= 5) {
                this.methodVisitor.visitInsn(Opcodes.ICONST_0 + i);
            } else if (i >= Byte.MIN_VALUE && i <= Byte.MAX_VALUE) {
                this.methodVisitor.visitIntInsn(Opcodes.BIPUSH, i);
            } else if (i >= Short.MIN_VALUE && i <= Short.MAX_VALUE) {
                this.methodVisitor.visitIntInsn(Opcodes.SIPUSH, i);
            } else {
                this.methodVisitor.visitLdcInsn(i);
            }
            return this;
        }

        @Info(
            """
            Add an instruction to push a long constant onto the operand stack.

            The method optimizes the instruction based on the value of the long:
            - For values 0L and 1L, it uses the `lconst_0` and `lconst_1` instructions respectively.
            - For all other values, it uses the `ldc` instruction.

            **Operand Stack:** (*l* is the pushed long constant. "---" is the second slot taken by the long.)

            { ... } → { ... , *l* , --- }

            @param l - The long constant to push onto the operand stack.
            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pushLong(long l) {
            if (l == 0L) {
                this.methodVisitor.visitInsn(Opcodes.LCONST_0);
            } else if (l == 1L) {
                this.methodVisitor.visitInsn(Opcodes.LCONST_1);
            } else {
                this.methodVisitor.visitLdcInsn(l);
            }
            return this;
        }

        @Info(
            """
            Add an instruction to push a float constant onto the operand stack.

            The method optimizes the instruction based on the value of the float:
            - For values 0.0f, 1.0f, and 2.0f, it uses the `fconst_0`, `fconst_1`, and `fconst_2` instructions respectively.
            - For all other values, it uses the `ldc` instruction.

            **Operand Stack:** (*f* is the pushed float constant.)

            { ... } → { ... , *f* }

            @param f - The float constant to push onto the operand stack.
            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pushFloat(float f) {
            if (f == 0.0f) {
                this.methodVisitor.visitInsn(Opcodes.FCONST_0);
            } else if (f == 1.0f) {
                this.methodVisitor.visitInsn(Opcodes.FCONST_1);
            } else if (f == 2.0f) {
                this.methodVisitor.visitInsn(Opcodes.FCONST_2);
            } else {
                this.methodVisitor.visitLdcInsn(f);
            }
            return this;
        }

        @Info(
            """
            Add an instruction to push a double constant onto the operand stack.

            The method optimizes the instruction based on the value of the double:
            - For values 0.0 and 1.0, it uses the `dconst_0` and `dconst_1` instructions respectively.
            - For all other values, it uses the `ldc` instruction.

            **Operand Stack:** (*d* is the pushed double constant. "---" is the second slot taken by the double.)

            { ... } → { ... , *d* , --- }

            @param d - The double constant to push onto the operand stack.
            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pushDouble(double d) {
            if (d == 0.0) {
                this.methodVisitor.visitInsn(Opcodes.DCONST_0);
            } else if (d == 1.0) {
                this.methodVisitor.visitInsn(Opcodes.DCONST_1);
            } else {
                this.methodVisitor.visitLdcInsn(d);
            }
            return this;
        }

        @Info(
            """
            Add an instruction to push a string constant onto the operand stack.

            The method uses the `ldc` instruction to push the string.

            **Operand Stack:** (*s* is the pushed string constant.)

            { ... } → { ... , *s* }

            @param s - The string constant to push onto the operand stack.
            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pushString(String s) {
            this.methodVisitor.visitLdcInsn(s);
            return this;
        }

        private int getVariableIndexOrThrow(String variableName, boolean isWideType) {
            int result = getVariableIndexOrThrow(variableName);
            if (this.localVariableTypes.get(result).equals(isWideType)) return result;
            throw new IllegalArgumentException("Local variable '" + variableName + "' is not of type '" + isWideType + "', but a '" +
                this.localVariableTypes.get(result) +"'.");
        }

        private int getVariableIndexOrThrow(String variableName) {
            int index = this.localVariableNames.indexOf(variableName);
            if (index == -1) {
                throw new IllegalArgumentException("Local variable '" + variableName + "' does not exist.");
            }
            return index;
        }

        private int getVariableIndexOrDeclare(String variableName) {
            int index = this.localVariableNames.indexOf(variableName);
            if (index == -1) {
                this.localVariableNames.add(variableName);
                this.localVariableTypes.add(false);
                index = this.localVariableNames.size() - 1;
            } else {
                boolean original = this.localVariableTypes.get(index);
                if (original) {
                    throw new IllegalArgumentException("Local variable '" + variableName + "' is of wide type.");
                }
                this.localVariableTypes.set(index, false);
            }
            return index;
        }

        // Push a null to the second slot of the wide variable into the variable table
        private int getVariableIndexOrDeclareWide(String variableName) {
            int index = this.localVariableNames.indexOf(variableName);
            if (index == -1) {
                this.localVariableNames.add(variableName);
                this.localVariableTypes.add(true);
                this.localVariableNames.add(null);
                this.localVariableTypes.add(null); // Dummy type for the wide slot
                index = this.localVariableNames.size() - 2;
            } else {
                boolean original = this.localVariableTypes.get(index);
                if (!original) {
                    throw new IllegalArgumentException("Local variable '" + variableName + "' is not of wide type.");
                }
                this.localVariableTypes.set(index, true);
            }
            return index;
        }

        @Info(
            """
            Add an `iload` instruction to the method.

            The `iload` instruction loads an integer from a local variable onto the operand stack.

            **Operand Stack:** (*i* is the loaded integer.)

            { ... } → { ... , *i* }

            @param variableName - The name of the local variable to load the integer from.
                Use `this` for instance methods to refer to the current object (if this method is an instance method).
                Parameters names are `arg0`, `arg1`, etc. at default.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable does not exist or is not of type `int`.
            """
        )
        public MethodCodeBuilder loadInt(String variableName) {
            int index = this.getVariableIndexOrThrow(variableName, false);
            this.methodVisitor.visitVarInsn(Opcodes.ILOAD, index);
            return this;
        }

        @Info(
            """
            Add an `lload` instruction to the method.

            The `lload` instruction loads a long from a local variable onto the operand stack.

            **Operand Stack:** (*l* is the loaded long and "---" is the second slot taken.)

            { ... } → { ... , *l* , --- }

            @param variableName - The name of the local variable to load the long from.
                Use `this` for instance methods to refer to the current object (if this method is an instance method).
                Parameters names are `arg0`, `arg1`, etc. at default.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable does not exist or is not of type `long`.
            """
        )
        public MethodCodeBuilder loadLong(String variableName) {
            int index = this.getVariableIndexOrThrow(variableName, true);
            this.methodVisitor.visitVarInsn(Opcodes.LLOAD, index);
            return this;
        }

        @Info(
            """
            Add an `fload` instruction to the method.

            The `fload` instruction loads a float from a local variable onto the operand stack.

            **Operand Stack:** (*f* is the loaded float.)

            { ... } → { ... , *f* }

            @param variableName - The name of the local variable to load the float from.
                Use `this` for instance methods to refer to the current object (if this method is an instance method).
                Parameters names are `arg0`, `arg1`, etc. at default.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable does not exist or is not of type `float`.
            """
        )
        public MethodCodeBuilder loadFloat(String variableName) {
            int index = this.getVariableIndexOrThrow(variableName, false);
            this.methodVisitor.visitVarInsn(Opcodes.FLOAD, index);
            return this;
        }

        @Info(
            """
            Add an `dload` instruction to the method.

            The `dload` instruction loads a double from a local variable onto the operand stack.

            **Operand Stack:** (*d* is the loaded double and "---" is the second slot taken.)

            { ... } → { ... , *d* , --- }

            @param variableName - The name of the local variable to load the double from.
                Use `this` for instance methods to refer to the current object (if this method is an instance method).
                Parameters names are `arg0`, `arg1`, etc. at default.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable does not exist or is not of type `double`.
            """
        )
        public MethodCodeBuilder loadDouble(String variableName) {
            int index = this.getVariableIndexOrThrow(variableName, true);
            this.methodVisitor.visitVarInsn(Opcodes.DLOAD, index);
            return this;
        }

        @Info(
            """
            Add an `aload` instruction to the method.

            The `aload` instruction loads an object reference from a local variable onto the operand stack.

            **Operand Stack:** (*object* is the loaded object reference.)

            { ... } → { ... , *object* }

            @param variableName - The name of the local variable to load the object from.
                Use `this` for instance methods to refer to the current object (if this method is an instance method).
                Parameters names are `arg0`, `arg1`, etc. at default.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable does not exist or is not of the required type.
            """
        )
        public MethodCodeBuilder loadObject(String variableName) {
            int index = this.getVariableIndexOrThrow(variableName, false);
            this.methodVisitor.visitVarInsn(Opcodes.ALOAD, index);
            return this;
        }

        @Info(
            """
            Add an `iaload` instruction to the method.

            The `iaload` instruction loads an integer from an integer array.

            **Operand Stack:** (*arrayref* is the reference to the integer array,
                and *index* is the index of the element to load.
                *i* is the loaded integer from the array.)

            { ... , *arrayref* , *index* } → { ... , *i* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder getIntFromArray() {
            this.methodVisitor.visitInsn(Opcodes.IALOAD);
            return this;
        }

        @Info(
            """
            Add an `laload` instruction to the method.

            The `laload` instruction loads a long from a long array.

            **Operand Stack:** (*arrayref* is the reference to the long array,
                and *index* is the index of the element to load.
                *l* is the loaded long from the array and "---" is the second slot taken.)

            { ... , *arrayref* , *index* } → { ... , *l* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder getLongFromArray() {
            this.methodVisitor.visitInsn(Opcodes.LALOAD);
            return this;
        }

        @Info(
            """
            Add a `faload` instruction to the method.

            The `faload` instruction loads a float from a float array.

            **Operand Stack:** (*arrayref* is the reference to the float array,
                and *index* is the index of the element to load.
                *f* is the loaded float from the array.)

            { ... , *arrayref* , *index* } → { ... , *f* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder getFloatFromArray() {
            this.methodVisitor.visitInsn(Opcodes.FALOAD);
            return this;
        }

        @Info(
            """
            Add a `daload` instruction to the method.

            The `daload` instruction loads a double from a double array.

            **Operand Stack:** (*arrayref* is the reference to the double array,
                and *index* is the index of the element to load.
                *d* is the loaded double from the array and "---" is the second slot taken.)

            { ... , *arrayref* , *index* } → { ... , *d* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder getDoubleFromArray() {
            this.methodVisitor.visitInsn(Opcodes.DALOAD);
            return this;
        }

        @Info(
            """
            Add an `aaload` instruction to the method.

            The `aaload` instruction loads an object reference from an object array.

            **Operand Stack:** (*arrayref* is the reference to the object array,
                and *index* is the index of the element to load.
                *object* is the loaded object reference from the array.)

            { ... , *arrayref* , *index* } → { ... , *object* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder getObjectFromArray() {
            this.methodVisitor.visitInsn(Opcodes.AALOAD);
            return this;
        }

        @Info(
            """
            Add a `baload` instruction to the method.

            The `baload` instruction loads a byte or boolean from a byte array.

            **Operand Stack:** (*arrayref* is the reference to the byte array,
                and *index* is the index of the element to load.
                *b* is the loaded byte or boolean from the array.)

            { ... , *arrayref* , *index* } → { ... , *b* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder getByteFromArray() {
            this.methodVisitor.visitInsn(Opcodes.BALOAD);
            return this;
        }

        @Info(
            """
            Add a `caload` instruction to the method.

            The `caload` instruction loads a char from a char array.

            **Operand Stack:** (*arrayref* is the reference to the char array,
                and *index* is the index of the element to load.
                *c* is the loaded char from the array.)

            { ... , *arrayref* , *index* } → { ... , *c* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder getCharFromArray() {
            this.methodVisitor.visitInsn(Opcodes.CALOAD);
            return this;
        }

        @Info(
            """
            Add a `saload` instruction to the method.

            The `saload` instruction loads a short from a short array.

            **Operand Stack:** (*arrayref* is the reference to the short array,
                and *index* is the index of the element to load.
                *s* is the loaded short from the array.)

            { ... , *arrayref* , *index* } → { ... , *s* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder getShortFromArray() {
            this.methodVisitor.visitInsn(Opcodes.SALOAD);
            return this;
        }

        @Info(
            """
            Add an `istore` instruction to the method.

            The `istore` instruction stores an integer from the operand stack into a local variable.

            **Note:** All *store* instructions *overrides* the variable type.

            **Operand Stack:** (*i* is the stored integer.)

            { ... , *i* } → { ... }

            @param variableName - The name of the local variable to store the integer into.
                Use `this` for instance methods to refer to the current object (if this method is an instance method).
                Parameters names are `arg0`, `arg1`, etc. at default. (Change them using `parameterNames(String[])` method before calling `code()`.)
                If the local variable does not exist, it will be created.
            @returns This `MethodCodeBuilder` instance.
            @throws `IllegalArgumentException` - if the local variable exists but is not of type `int`.
            """
        )
        public MethodCodeBuilder storeInt(String variableName) {
            int index = this.getVariableIndexOrDeclare(variableName);
            this.methodVisitor.visitVarInsn(Opcodes.ISTORE, index);
            return this;
        }

        @Info(
            """
            Add an `lstore` instruction to the method.

            The `lstore` instruction stores a long from the operand stack into a local variable.

            **Note:** All *store* instructions *overrides* the variable type.

            **Operand Stack:** (*l* is the stored long and "---" is the second slot taken.)

            { ... , *l* , --- } → { ... }

            @param variableName - The name of the local variable to store the long into.
                If the local variable does not exist, it will be created.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable exists but is not of type `long`.
            """
        )
        public MethodCodeBuilder storeLong(String variableName) {
            int index = this.getVariableIndexOrDeclareWide(variableName);
            this.methodVisitor.visitVarInsn(Opcodes.LSTORE, index);
            return this;
        }

        @Info(
            """
            Add an `fstore` instruction to the method.

            The `fstore` instruction stores a float from the operand stack into a local variable.

            **Note:** All *store* instructions *overrides* the variable type.

            **Operand Stack:** (*f* is the stored float.)

            { ... , *f* } → { ... }

            @param variableName - The name of the local variable to store the float into.
                If the local variable does not exist, it will be created.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable exists but is not of type `float`.
            """
        )
        public MethodCodeBuilder storeFloat(String variableName) {
            int index = this.getVariableIndexOrDeclare(variableName);
            this.methodVisitor.visitVarInsn(Opcodes.FSTORE, index);
            return this;
        }

        @Info(
            """
            Add an `dstore` instruction to the method.

            The `dstore` instruction stores a double from the operand stack into a local variable.

            **Note:** All *store* instructions *overrides* the variable type.

            **Operand Stack:** (*d* is the stored double and "---" is the second slot taken.)

            { ... , *d* , --- } → { ... }

            @param variableName - The name of the local variable to store the double into.
                If the local variable does not exist, it will be created.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable exists but is not of type `double`.
            """
        )
        public MethodCodeBuilder storeDouble(String variableName) {
            int index = this.getVariableIndexOrDeclareWide(variableName);
            this.methodVisitor.visitVarInsn(Opcodes.DSTORE, index);
            return this;
        }

        @Info(
            """
            Add an `astore` instruction to the method.

            The `astore` instruction stores an object reference from the operand stack into a local variable.

            **Note:** All *store* instructions *overrides* the variable type.

            **Operand Stack:** (*object* is the stored object reference.)

            { ... , *object* } → { ... }

            @param variableName - The name of the local variable to store the object into.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable exists but is not of an object type.
            """
        )
        public MethodCodeBuilder storeObject(String variableName) {
            int index = this.getVariableIndexOrDeclare(variableName);
            this.methodVisitor.visitVarInsn(Opcodes.ASTORE, index);
            return this;
        }

        @Info(
            """
            Add an `iastore` instruction to the method.

            The `iastore` instruction stores an integer into an integer array.

            **Operand Stack:** (*arrayref* is the reference to the integer array,
                *index* is the index of the element to store, and *value* is the integer to store.)

            { ... , *arrayref* , *index* , *value* } → { ... }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder putIntToArray() {
            this.methodVisitor.visitInsn(Opcodes.IASTORE);
            return this;
        }

        @Info(
            """
            Add an `lastore` instruction to the method.

            The `lastore` instruction stores a long into a long array.

            **Operand Stack:** (*arrayref* is the reference to the long array,
                *index* is the index of the element to store, and *value* is the long to store.
                "---" is the second slot taken by the long.)

            { ... , *arrayref* , *index* , *value* , --- } → { ... }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder putLongToArray() {
            this.methodVisitor.visitInsn(Opcodes.LASTORE);
            return this;
        }

        @Info(
            """
            Add a `fastore` instruction to the method.

            The `fastore` instruction stores a float into a float array.

            **Operand Stack:** (*arrayref* is the reference to the float array,
                *index* is the index of the element to store, and *value* is the float to store.)

            { ... , *arrayref* , *index* , *value* } → { ... }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder putFloatToArray() {
            this.methodVisitor.visitInsn(Opcodes.FASTORE);
            return this;
        }

        @Info(
            """
            Add a `dastore` instruction to the method.

            The `dastore` instruction stores a double into a double array.

            **Operand Stack:** (*arrayref* is the reference to the double array,
                *index* is the index of the element to store, and *value* is the double to store.
                "---" is the second slot taken by the double.)

            { ... , *arrayref* , *index* , *value* , --- } → { ... }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder putDoubleToArray() {
            this.methodVisitor.visitInsn(Opcodes.DASTORE);
            return this;
        }

        @Info(
            """
            Add an `aastore` instruction to the method.

            The `aastore` instruction stores an object reference into an object array.

            **Operand Stack:** (*arrayref* is the reference to the object array,
                *index* is the index of the element to store, and *value* is the object reference to store.)

            { ... , *arrayref* , *index* , *value* } → { ... }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder putObjectToArray() {
            this.methodVisitor.visitInsn(Opcodes.AASTORE);
            return this;
        }

        @Info(
            """
            Add a `bastore` instruction to the method.

            The `bastore` instruction stores a byte or boolean into a byte array.

            **Operand Stack:** (*arrayref* is the reference to the byte array,
                *index* is the index of the element to store, and *value* is the byte or boolean to store.)

            { ... , *arrayref* , *index* , *value* } → { ... }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder putByteToArray() {
            this.methodVisitor.visitInsn(Opcodes.BASTORE);
            return this;
        }

        @Info(
            """
            Add a `castore` instruction to the method.

            The `castore` instruction stores a char into a char array.

            **Operand Stack:** (*arrayref* is the reference to the char array,
                *index* is the index of the element to store, and *value* is the char to store.)

            { ... , *arrayref* , *index* , *value* } → { ... }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder putCharToArray() {
            this.methodVisitor.visitInsn(Opcodes.CASTORE);
            return this;
        }

        @Info(
            """
            Add a `sastore` instruction to the method.

            The `sastore` instruction stores a short into a short array.

            **Operand Stack:** (*arrayref* is the reference to the short array,
                *index* is the index of the element to store, and *value* is the short to store.)

            { ... , *arrayref* , *index* , *value* } → { ... }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder putShortToArray() {
            this.methodVisitor.visitInsn(Opcodes.SASTORE);
            return this;
        }

        @Info(
            """
            Add a `pop` instruction to the method.

            The `pop` instruction removes the top value from the operand stack.

            **Note:** This instruction can only be used to pop values that take up one slot (e.g., int, float, reference).
                For removing longs and doubles, use the `pop2` instruction instead.

            **Operand Stack:** (*v* is the popped value.)

            { ... , *v* } → { ... }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pop() {
            this.methodVisitor.visitInsn(Opcodes.POP);
            return this;
        }

        @Info(
            """
            Add a `pop2` instruction to the method.

            The `pop2` instruction removes the top one or two values from the operand stack.

            **Operand Stack:**

            - If the top value is a long or double: (*v1* is the popped long or double, and "---" is the second slot taken.)
              - { ... , *v1* , --- } → { ... }

            - Otherwise: (*v1* and *v2* are the popped values and neither of them is a long or a double.)
              - { ... , *v2* , *v1* } → { ... }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pop2() {
            this.methodVisitor.visitInsn(Opcodes.POP2);
            return this;
        }

        @Info(
            """
            Add a `dup` instruction to the method.

            The `dup` instruction duplicates the top value on the operand stack.

            **Note:** This instruction can only be used to duplicate values that are neither longs nor doubles.
                For duplicating longs and doubles, use the `dup2` instruction instead.

            **Operand Stack:** (*v* is the duplicated value.)

            { ... , *v* } → { ... , *v* , *v* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder duplicate() {
            this.methodVisitor.visitInsn(Opcodes.DUP);
            return this;
        }

        @Info(
            """
            Add a `dup_x1` instruction to the method.

            The `dup_x1` instruction duplicates the top value on the operand stack and inserts it two values down.

            **Operand Stack:** (*v1* is the duplicated value, and *v2* is the value below it.
                Neither *v1* nor *v2* can be a long or a double.)

            { ... , *v2* , *v1* } → { ... , *v1* , *v2* , *v1* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder duplicateX1() {
            this.methodVisitor.visitInsn(Opcodes.DUP_X1);
            return this;
        }

        @Info(
            """
            Add a `dup_x2` instruction to the method.

            The `dup_x2` instruction duplicates the top value on the operand stack and inserts it two or three values down.

            **Operand Stack:**

            - If the second value is a long or double: (*v1* is the duplicated value, *v2* is the long or double, and "---" is the second slot taken.)
              - { ... , *v2* , --- , *v1* } → { ... , *v1* , *v2* , --- , *v1* }

            - Otherwise: (*v1*, *v2*, and *v3* are the values, and none of them is a long or a double.)
              - { ... , *v3* , *v2* , *v1* } → { ... , *v1* , *v3* , *v2* , *v1* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder duplicateX2() {
            this.methodVisitor.visitInsn(Opcodes.DUP_X2);
            return this;
        }

        @Info(
            """
            Add a `dup2` instruction to the method.

            The `dup2` instruction duplicates the top one or two values on the operand stack.

            **Operand Stack:**

            - If the top value is a long or double: (*v1* is the duplicated long or double, and "---" is the second slot taken.)
              - { ... , *v1* , --- } → { ... , *v1* , --- , *v1* , --- }

            - Otherwise: (*v1* and *v2* are the duplicated values and neither of them is a long or a double.)
              - { ... , *v2* , *v1* } → { ... , *v2* , *v1* , *v2* , *v1* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder duplicate2() {
            this.methodVisitor.visitInsn(Opcodes.DUP2);
            return this;
        }

        @Info(
            """
            Add a `dup2_x1` instruction to the method.

            The `dup2_x1` instruction duplicates the top one or two values on the operand stack and inserts them two or three values down.

            **Operand Stack:**

            - If the top value is a long or double: (*v1* is the duplicated long or double, *v2* is the value below it, and "---" is the second slot taken.)
              - { ... , *v2* , *v1* , --- } → { ... , *v1* , --- , *v2* , *v1* , --- }

            - Otherwise: (*v1* and *v2* are the duplicated values, *v3* is the value below them, and none of them is a long or a double.)
              - { ... , *v3* , *v2* , *v1* } → { ... , *v2* , *v1* , *v3* , *v2* , *v1* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder duplicate2X1() {
            this.methodVisitor.visitInsn(Opcodes.DUP2_X1);
            return this;
        }

        @Info(
            """
            Add a `dup2_x2` instruction to the method.

            The `dup2_x2` instruction duplicates the top one or two values on the operand stack and inserts them two, three, or four values down.

            **Operand Stack:**

            - If the top value is a long or double and the second value is also a long or double:
                (*v1* is the duplicated long or double, *v2* is the long or double below it, and "---" are the second slots taken.)
                - { ... , *v2* , --- , *v1* , --- } → { ... , *v1* , --- , *v2* , --- , *v1* , --- }

            - If the top value is a long or double and the second value is not:
                (*v1* is the duplicated long or double, *v2* is the value below it, and "---" is the second slot taken.)
                - { ... , *v2* , *v1* , --- } → { ... , *v1* , --- , *v2* , *v1* , --- }

            - If neither of the top two values is a long or double and the third value is a long or double:
                (*v1* and *v2* are the duplicated values, *v3* is the long or double below them, and "---" is the second slot taken.)
                - { ... , *v3* , --- , *v2* , *v1* } → { ... , *v2* , *v1* , *v3* , --- , *v2* , *v1* }

            - If none of the top three values is a long or double:
                (*v1*, *v2*, and *v3* are the values, and none of them is a long or a double.)
                - { ... , *v4* , *v3* , *v2* , *v1* } → { ... , *v2* , *v1* , *v4* , *v3* , *v2* , *v1* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder duplicate2X2() {
            this.methodVisitor.visitInsn(Opcodes.DUP2_X2);
            return this;
        }

        @Info(
            """
            Add a `swap` instruction to the method.

            The `swap` instruction swaps the top two values on the operand stack.

            **Note:** This instruction can only be used to swap values that are neither longs nor doubles.
                For swapping longs and doubles, you need to use a combination of `dup` and `pop` instructions.

            **Operand Stack:** (*v1* and *v2* are the values to be swapped, and neither of them is a long or a double.)

            { ... , *v2* , *v1* } → { ... , *v1* , *v2* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder swap() {
            this.methodVisitor.visitInsn(Opcodes.SWAP);
            return this;
        }

        @Info(
            """
            Add an `iadd` instruction to the method.

            The `iadd` instruction adds the top two integers on the operand stack.

            **Operand Stack:** (*i1* and *i2* are the integers to be added, and *result* is *i1* + *i2*.)

            { ... , *i1* , *i2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder intAdd() {
            this.methodVisitor.visitInsn(Opcodes.IADD);
            return this;
        }

        @Info(
            """
            Add an `ladd` instruction to the method.

            The `ladd` instruction adds the top two longs on the operand stack.

            **Operand Stack:** (*l1* and *l2* are the longs to be added, "---" are the second slots taken,
                and *result* is *l1* + *l2*.)

            { ... , *l1* , --- , *l2* , --- } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder longAdd() {
            this.methodVisitor.visitInsn(Opcodes.LADD);
            return this;
        }

        @Info(
            """
            Add an `fadd` instruction to the method.

            The `fadd` instruction adds the top two floats on the operand stack.

            **Operand Stack:** (*f1* and *f2* are the floats to be added, and *result* is *f1* + *f2*.)

            { ... , *f1* , *f2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder floatAdd() {
            this.methodVisitor.visitInsn(Opcodes.FADD);
            return this;
        }

        @Info(
            """
            Add a `dadd` instruction to the method.

            The `dadd` instruction adds the top two doubles on the operand stack.

            **Operand Stack:** (*d1* and *d2* are the doubles to be added, "---" are the second slots taken,
                and *result* is *d1* + *d2*.)

            { ... , *d1* , --- , *d2* , --- } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder doubleAdd() {
            this.methodVisitor.visitInsn(Opcodes.DOUBLE);
            return this;
        }

        @Info(
            """
            Add an `isub` instruction to the method.

            The `isub` instruction subtracts the top integer on the operand stack from the second top integer.

            **Operand Stack:** (*i1* and *i2* are the integers to be subtracted, and *result* is *i1* - *i2*.)

            { ... , *i1* , *i2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder intSub() {
            this.methodVisitor.visitInsn(Opcodes.ISUB);
            return this;
        }

        @Info(
            """
            Add an `lsub` instruction to the method.

            The `lsub` instruction subtracts the top long on the operand stack from the second top long.

            **Operand Stack:** (*l1* and *l2* are the longs to be subtracted, "---" are the second slots taken,
                and *result* is *l1* - *l2*.)

            { ... , *l1* , --- , *l2* , --- } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder longSub() {
            this.methodVisitor.visitInsn(Opcodes.LSUB);
            return this;
        }

        @Info(
            """
            Add an `fsub` instruction to the method.

            The `fsub` instruction subtracts the top float on the operand stack from the second top float.

            **Operand Stack:** (*f1* and *f2* are the floats to be subtracted, and *result* is *f1* - *f2*.)

            { ... , *f1* , *f2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder floatSub() {
            this.methodVisitor.visitInsn(Opcodes.FSUB);
            return this;
        }

        @Info(
            """
            Add a `dsub` instruction to the method.

            The `dsub` instruction subtracts the top double on the operand stack from the second top double.

            **Operand Stack:** (*d1* and *d2* are the doubles to be subtracted, "---" are the second slots taken,
                and *result* is *d1* - *d2*.)

            { ... , *d1* , --- , *d2* , --- } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder doubleSub() {
            this.methodVisitor.visitInsn(Opcodes.DSUB);
            return this;
        }

        @Info(
            """
            Add an `imul` instruction to the method.

            The `imul` instruction multiplies the top two integers on the operand stack.

            **Operand Stack:** (*i1* and *i2* are the integers to be multiplied, and *result* is *i1* \\* *i2*.)

            { ... , *i1* , *i2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder intMul() {
            this.methodVisitor.visitInsn(Opcodes.IMUL);
            return this;
        }

        @Info(
            """
            Add an `lmul` instruction to the method.

            The `lmul` instruction multiplies the top two longs on the operand stack.

            **Operand Stack:** (*l1* and *l2* are the longs to be multiplied, "---" are the second slots taken,
                and *result* is *l1* \\* *l2*.)

            { ... , *l1* , --- , *l2* , --- } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder longMul() {
            this.methodVisitor.visitInsn(Opcodes.LMUL);
            return this;
        }

        @Info(
            """
            Add an `fmul` instruction to the method.

            The `fmul` instruction multiplies the top two floats on the operand stack.

            **Operand Stack:** (*f1* and *f2* are the floats to be multiplied, and *result* is *f1* \\* *f2*.)

            { ... , *f1* , *f2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder floatMul() {
            this.methodVisitor.visitInsn(Opcodes.FMUL);
            return this;
        }

        @Info(
            """
            Add a `dmul` instruction to the method.

            The `dmul` instruction multiplies the top two doubles on the operand stack.

            **Operand Stack:** (*d1* and *d2* are the doubles to be multiplied, "---" are the second slots taken,
                and *result* is *d1* \\* *d2*.)

            { ... , *d1* , --- , *d2* , --- } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder doubleMul() {
            this.methodVisitor.visitInsn(Opcodes.DMUL);
            return this;
        }

        @Info(
            """
            Add an `idiv` instruction to the method.

            The `idiv` instruction divides the second top integer on the operand stack by the top integer.

            **Operand Stack:** (*i1* and *i2* are the integers to be divided, and *result* is *i1* / *i2*.)

            { ... , *i1* , *i2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder intDiv() {
            this.methodVisitor.visitInsn(Opcodes.IDIV);
            return this;
        }

        @Info(
            """
            Add an `ldiv` instruction to the method.

            The `ldiv` instruction divides the second top long on the operand stack by the top long.

            **Operand Stack:** (*l1* and *l2* are the longs to be divided, "---" are the second slots taken,
                and *result* is *l1* / *l2*.)

            { ... , *l1* , --- , *l2* , --- } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder longDiv() {
            this.methodVisitor.visitInsn(Opcodes.LDIV);
            return this;
        }

        @Info(
            """
            Add an `fdiv` instruction to the method.

            The `fdiv` instruction divides the second top float on the operand stack by the top float.

            **Operand Stack:** (*f1* and *f2* are the floats to be divided, and *result* is *f1* / *f2*.)

            { ... , *f1* , *f2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder floatDiv() {
            this.methodVisitor.visitInsn(Opcodes.FDIV);
            return this;
        }

        @Info(
            """
            Add a `ddiv` instruction to the method.

            The `ddiv` instruction divides the second top double on the operand stack by the top double.

            **Operand Stack:** (*d1* and *d2* are the doubles to be divided, "---" are the second slots taken,
                and *result* is *d1* / *d2*.)

            { ... , *d1* , --- , *d2* , --- } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder doubleDiv() {
            this.methodVisitor.visitInsn(Opcodes.DDIV);
            return this;
        }

        @Info(
            """
            Add an `irem` instruction to the method.

            The `irem` instruction computes the remainder of the division of the second top integer on the operand stack by the top integer.

            **Operand Stack:** (*i1* and *i2* are the integers, and *result* is *i1* % *i2*.)

            { ... , *i1* , *i2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder intRem() {
            this.methodVisitor.visitInsn(Opcodes.IREM);
            return this;
        }

        @Info(
            """
            Add an `lrem` instruction to the method.

            The `lrem` instruction computes the remainder of the division of the second top long on the operand stack by the top long.

            **Operand Stack:** (*l1* and *l2* are the longs, "---" are the second slots taken,
                and *result* is *l1* % *l2*.)

            { ... , *l1* , --- , *l2* , --- } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder longRem() {
            this.methodVisitor.visitInsn(Opcodes.LREM);
            return this;
        }

        @Info(
            """
            Add an `frem` instruction to the method.

            The `frem` instruction computes the remainder of the division of the second top float on the operand stack by the top float.

            **Operand Stack:** (*f1* and *f2* are the floats, and *result* is *f1* % *f2*.)

            { ... , *f1* , *f2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder floatRem() {
            this.methodVisitor.visitInsn(Opcodes.FREM);
            return this;
        }

        @Info(
            """
            Add a `drem` instruction to the method.

            The `drem` instruction computes the remainder of the division of the second top double on the operand stack by the top double.

            **Operand Stack:** (*d1* and *d2* are the doubles, "---" are the second slots taken,
                and *result* is *d1* % *d2*.)

            { ... , *d1* , --- , *d2* , --- } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder doubleRem() {
            this.methodVisitor.visitInsn(Opcodes.DREM);
            return this;
        }

        @Info(
            """
            Add an `ineg` instruction to the method.

            The `ineg` instruction negates the top integer on the operand stack.

            **Operand Stack:** (*i* is the integer to be negated, and *result* is -*i*.)

            { ... , *i* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder intNeg() {
            this.methodVisitor.visitInsn(Opcodes.INEG);
            return this;
        }

        @Info(
            """
            Add an `lneg` instruction to the method.

            The `lneg` instruction negates the top long on the operand stack.

            **Operand Stack:** (*l* is the long to be negated, "---" is the second slot taken,
                and *result* is -*l*.)

            { ... , *l* , --- } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder longNeg() {
            this.methodVisitor.visitInsn(Opcodes.LNEG);
            return this;
        }

        @Info(
            """
            Add an `fneg` instruction to the method.

            The `fneg` instruction negates the top float on the operand stack.

            **Operand Stack:** (*f* is the float to be negated, and *result* is -*f*.)

            { ... , *f* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder floatNeg() {
            this.methodVisitor.visitInsn(Opcodes.FNEG);
            return this;
        }

        @Info(
            """
            Add a `dneg` instruction to the method.

            The `dneg` instruction negates the top double on the operand stack.

            **Operand Stack:** (*d* is the double to be negated, "---" is the second slot taken,
                and *result* is -*d*.)

            { ... , *d* , --- } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder doubleNeg() {
            this.methodVisitor.visitInsn(Opcodes.DNEG);
            return this;
        }

        @Info(
            """
            Add an `ishl` instruction to the method.

            The `ishl` instruction performs a left shift on the top integer on the operand stack by the number of bits specified by the second top integer.

            **Operand Stack:** (*i1* is the integer to be shifted, *i2* is the number of bits to shift,
                and *result* is *i1* << *i2*.)

            { ... , *i1* , *i2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder intLShift() {
            this.methodVisitor.visitInsn(Opcodes.ISHL);
            return this;
        }

        @Info(
            """
            Add an `lshl` instruction to the method.

            The `lshl` instruction performs a left shift on the top long on the operand stack by the number of bits specified by the second top integer.

            **Operand Stack:** (*l* is the long to be shifted, "---" is the second slot taken,
                *i* is the number of bits to shift, and *result* is *l* << *i*.)

            { ... , *l* , --- , *i* } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder longLShift() {
            this.methodVisitor.visitInsn(Opcodes.LSHL);
            return this;
        }

        @Info(
            """
            Add an `ishr` instruction to the method.

            The `ishr` instruction performs an arithmetic right shift on the top integer on the operand stack by the number of bits specified by the second top integer.

            **Operand Stack:** (*i1* is the integer to be shifted, *i2* is the number of bits to shift,
                and *result* is *i1* >> *i2*.)

            { ... , *i1* , *i2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder intRShift() {
            this.methodVisitor.visitInsn(Opcodes.ISHR);
            return this;
        }

        @Info(
            """
            Add an `lshr` instruction to the method.

            The `lshr` instruction performs an arithmetic right shift on the top long on the operand stack by the number of bits specified by the second top integer.

            **Operand Stack:** (*l* is the long to be shifted, "---" is the second slot taken,
                *i* is the number of bits to shift, and *result* is the shifted long.)

            { ... , *l* , --- , *i* } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder longRShift() {
            this.methodVisitor.visitInsn(Opcodes.LSHR);
            return this;
        }

        @Info(
            """
            Add an `iushr` instruction to the method.

            The `iushr` instruction performs a logical right shift on the top integer on the operand stack by the number of bits specified by the second top integer.

            **Operand Stack:** (*i1* is the integer to be shifted, *i2* is the number of bits to shift,
                and *result* is *i1* >>> *i2*.)

            { ... , *i1* , *i2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder intRShiftLogical() {
            this.methodVisitor.visitInsn(Opcodes.IUSHR);
            return this;
        }

        @Info(
            """
            Add an `lushr` instruction to the method.

            The `lushr` instruction performs a logical right shift on the top long on the operand stack by the number of bits specified by the second top integer.

            **Operand Stack:** (*l* is the long to be shifted, "---" is the second slot taken,
                *i* is the number of bits to shift, and *result* is *l* >>> *i*.)

            { ... , *l* , --- , *i* } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder longRShiftLogical() {
            this.methodVisitor.visitInsn(Opcodes.LUSHR);
            return this;
        }

        @Info(
            """
            Add an `iand` instruction to the method.

            The `iand` instruction performs a bitwise AND operation on the top two integers on the operand stack.

            **Operand Stack:** (*i1* and *i2* are the integers to be ANDed, and *result* is *i1* & *i2*.)

            { ... , *i1* , *i2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder intAnd() {
            this.methodVisitor.visitInsn(Opcodes.IAND);
            return this;
        }

        @Info(
            """
            Add an `land` instruction to the method.

            The `land` instruction performs a bitwise AND operation on the top two longs on the operand stack.

            **Operand Stack:** (*l1* and *l2* are the longs to be ANDed, "---" are the second slots taken,
                and *result* is *l1* & *l2*.)

            { ... , *l1* , --- , *l2* , --- } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder longAnd() {
            this.methodVisitor.visitInsn(Opcodes.LAND);
            return this;
        }

        @Info(
            """
            Add an `ior` instruction to the method.

            The `ior` instruction performs a bitwise OR operation on the top two integers on the operand stack.

            **Operand Stack:** (*i1* and *i2* are the integers to be ORed, and *result* is *i1* | *i2*.)

            { ... , *i1* , *i2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder intOr() {
            this.methodVisitor.visitInsn(Opcodes.IOR);
            return this;
        }

        @Info(
            """
            Add a `lor` instruction to the method.

            The `lor` instruction performs a bitwise OR operation on the top two longs on the operand stack.

            **Operand Stack:** (*l1* and *l2* are the longs to be ORed, "---" are the second slots taken,
                and *result* is *l1* | *l2*.)

            { ... , *l1* , --- , *l2* , --- } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder longOr() {
            this.methodVisitor.visitInsn(Opcodes.LOR);
            return this;
        }

        @Info(
            """
            Add an `ixor` instruction to the method.

            The `ixor` instruction performs a bitwise XOR operation on the top two integers on the operand stack.

            **Operand Stack:** (*i1* and *i2* are the integers to be XORed, and *result* is *i1* ^ *i2*.)

            { ... , *i1* , *i2* } → { ... , *result* }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder IntXor() {
            this.methodVisitor.visitInsn(Opcodes.IXOR);
            return this;
        }

        @Info(
            """
            Add a `lxor` instruction to the method.

            The `lxor` instruction performs a bitwise XOR operation on the top two longs on the operand stack.

            **Operand Stack:** (*l1* and *l2* are the longs to be XORed, "---" are the second slots taken,
                and *result* is *l1* ^ *l2*.)

            { ... , *l1* , --- , *l2* , --- } → { ... , *result* , --- }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder longXor() {
            this.methodVisitor.visitInsn(Opcodes.LXOR);
            return this;
        }

        @Info(
            """
            Add an `iinc` instruction to the method to increment a local integer variable by a specified constant.

            The `iinc` instruction increments the value of a local variable by a constant value.
            This instruction is specifically designed for local variables of type `int`.

            **Operand Stack:**

            { ... } → { ... }

            @param varIndex - The index of the local variable to be incremented. Must be a non-negative integer.
            @param increment - The constant value to add to the local variable. Can be positive or negative.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if `varIndex` is negative.
            """
        )
        public MethodCodeBuilder intIncrease(int varIndex, int increment) {
            this.methodVisitor.visitIincInsn(varIndex, increment);
            return this;
        }

        @Info(
            """
            Add a `ireturn` instruction to the method.

            The `ireturn` instruction is used to return an integer from a method.
            Before `ireturn`, the operand stack must have ***one and only one*** integer value.

            **Operand Stack:** (*i* is the returned integer.)

            { *i* } → [*EMPTY*]

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder returnInt() {
            this.methodVisitor.visitInsn(Opcodes.IRETURN);
            return this;
        }

        @Info(
            """
            Add a `lreturn` instruction to the method.

            The `lreturn` instruction is used to return a long from a method.
            Before `lreturn`, the operand stack must have ***one and only one*** long value (which takes two slots).

            **Operand Stack:** (*l* is the returned long. "---" is the second slot taken by the long.)

            { *l* , --- } → [*EMPTY*]

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder returnLong() {
            this.methodVisitor.visitInsn(Opcodes.LRETURN);
            return this;
        }

        @Info(
            """
            Add a `freturn` instruction to the method.

            The `freturn` instruction is used to return a float from a method.
            Before `freturn`, the operand stack must have ***one and only one*** float value.

            **Operand Stack:** (*f* is the returned float.)

            { *f* } → [*EMPTY*]

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder returnFloat() {
            this.methodVisitor.visitInsn(Opcodes.FRETURN);
            return this;
        }

        @Info(
            """
            Add a `dreturn` instruction to the method.

            The `dreturn` instruction is used to return a double from a method.
            Before `dreturn`, the operand stack must have ***one and only one*** double value (which takes two slots).

            **Operand Stack:** (*d* is the returned double. "---" is the second slot taken by the double.)

            { *d* , --- } → [*EMPTY*]

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder returnDouble() {
            this.methodVisitor.visitInsn(Opcodes.DRETURN);
            return this;
        }

        @Info(
            """
            Add an `areturn` instruction to the method.

            The `areturn` instruction is used to return a reference from a method.
            Before `areturn`, the operand stack must have ***one and only one*** reference value.

            **Operand Stack:** (*o* is the returned reference.)

            { *o* } → [*EMPTY*]

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder returnObject() {
            this.methodVisitor.visitInsn(Opcodes.ARETURN);
            return this;
        }

        @Info(
            """
            Add a `return` instruction to the method.

            The `return` instruction is used to return from a method that has a `void` return type.
            Before `return`, the operand stack must be ***empty***.

            **Operand Stack:**

            [*EMPTY*] → [*EMPTY*]

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder returnVoid() {
            this.methodVisitor.visitInsn(Opcodes.RETURN);
            return this;
        }

        @Info(
            """
            Add a `newarray` instruction to the method to create a new array of a specified primitive type.

            The `newarray` instruction creates a new array of the specified primitive type and pushes its reference onto the operand stack.
            The size of the array is determined by the integer value on the top of the operand stack.

            Supported primitive types are:
            - `boolean`
            - `char`
            - `float`
            - `double`
            - `byte`
            - `short`
            - `int`
            - `long`

            **Operand Stack:** (*count* is the number of elements in the new array, and *arrayref* is the reference to the new array.)

            { ... , *count* } → { ... , *arrayref* }

            @param elementType - The type of elements in the new array. Must be one of the supported primitive types.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the specified element type is not supported.
            """
        )
        public MethodCodeBuilder newArray(String elementType) {
            int atype = switch (elementType) {
                case "boolean" -> 4;
                case "char" -> 5;
                case "float" -> 6;
                case "double" -> 7;
                case "byte" -> 8;
                case "short" -> 9;
                case "int" -> 10;
                case "long" -> 11;
                default -> {
                    throw new IllegalArgumentException("Unsupported array type: " + elementType);
                }
            };
            this.methodVisitor.visitIntInsn(Opcodes.NEWARRAY, atype);
            return this;
        }

        @Info(
            """
            Add a `anewarray` instruction to the method to create a new array of a specified reference type.

            The `anewarray` instruction creates a new array of the specified reference type and pushes its reference onto the operand stack.
            The size of the array is determined by the integer value on the top of the operand stack.

            **Operand Stack:** (*count* is the number of elements in the new array, and *arrayref* is the reference to the new array.)

            { ... , *count* } → { ... , *arrayref* }

            @param elementType - The name of the class or interface of the elements in the new array (e.g., `java.lang.String` for an array of `String`).
            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder newObjectArray(String elementType) {
            String descriptor = DescriptorUtils.toFieldDescriptor(elementType);
            this.methodVisitor.visitTypeInsn(Opcodes.ANEWARRAY, descriptor);
            return this;
        }

        @Info(
            """
            Ends the method creation and returns to the parent `ClassCreator`.

            **Note:** Do not try to add any codes after this method.
            They may cause undefined behaviors.

            @returns The parent `ClassCreator`.
            
            **Note**: The returned is ***NOT*** the parent `MethodCreator`, but the `ClassCreator`.
            """
        )
        public ClassCreator build() {
            methodVisitor.visitMaxs(0, 0);
            methodVisitor.visitEnd();
            return this.parent.parent;
        }

    }

}
