package pelemenguin.classjs.content;

import java.util.ArrayList;

import org.objectweb.asm.MethodVisitor;
import org.objectweb.asm.Opcodes;

import dev.latvian.mods.kubejs.typings.Info;
import pelemenguin.util.DescriptorUtils;

public class MethodCreator {

    private ClassCreator parent;

    private int access = 0;
    private String name;
    private String descriptor;

    // Parameter names used in MethodCodeBuilder
    private String[] paramNames;
    
    public MethodCreator(ClassCreator parent, String name, String[] parameterTypes, String returnType) {
        this.parent = parent;
        this.name = name;
        this.descriptor = DescriptorUtils.toMethodDescriptor(parameterTypes, returnType);
    }

    @Info(
        """
        Remove `public`, `private`, and `protected` modifiers from this method.
        Such a method can only be accessed from classes in the same package.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toDefault() {
        this.access &= ~(Opcodes.ACC_PUBLIC | Opcodes.ACC_PRIVATE | Opcodes.ACC_PROTECTED);
        return this;
    }

    @Info(
        """
        Set the method to `public`.
        A *public* method can be accessed from any other class.

        **Note:** Interface methods *must* set this flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toPublic() {
        this.toDefault();
        this.access |= Opcodes.ACC_PUBLIC;
        return this;
    }

    @Info(
        """
        Set the method to `private`.
        A *private* method can only be accessed from within the same class.

        **Note:** This flag *cannot* be set together with `abstract` flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toPrivate() {
        this.toDefault();
        this.access |= Opcodes.ACC_PRIVATE;
        return this;
    }

    @Info(
        """
        Set the method to `protected`.
        A *protected* method can be accessed from classes in the same package and subclasses.

        **Note:** Interface methods *cannot* set this flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toProtected() {
        this.toDefault();
        this.access |= Opcodes.ACC_PROTECTED;
        return this;
    }

    @Info(
        """
        Set the method to `static`.
        A *static* method belongs to the class rather than an instance of the class.

        **Note:** This flag *cannot* be set together with `abstract` flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toStatic() {
        this.access |= Opcodes.ACC_STATIC;
        return this;
    }

    @Info(
        """
        Remove the `static` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notStatic() {
        this.access &= ~Opcodes.ACC_STATIC;
        return this;
    }

    @Info(
        """
        Set the method to `final`.
        A *final* method cannot be overridden by subclasses.

        **Note:** Interface methods *cannot* set this flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toFinal() {
        this.access |= Opcodes.ACC_FINAL;
        return this;
    }

    @Info(
        """
        Remove the `final` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notFinal() {
        this.access &= ~Opcodes.ACC_FINAL;
        return this;
    }

    @Info(
        """
        Set the method to `synchronized`.
        A *synchronized* method can only be accessed by one thread at a time.

        **Note:** Interface methods *cannot* set this flag.
            This flag *cannot* be set together with `abstract` flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toSynchronized() {
        this.access |= Opcodes.ACC_SYNCHRONIZED;
        return this;
    }

    @Info(
        """
        Remove the `synchronized` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notSynchronized() {
        this.access &= ~Opcodes.ACC_SYNCHRONIZED;
        return this;
    }

    @Info(
        """
        Set the method to be a `bridge` method.
        A *bridge* method is a synthetic method that is generated by the compiler to handle type erasure in generics.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toBridge() {
        this.access |= Opcodes.ACC_BRIDGE;
        return this;
    }

    @Info(
        """
        Remove the `bridge` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notBridge() {
        this.access &= ~Opcodes.ACC_BRIDGE;
        return this;
    }

    @Info(
        """
        Set the method to be a `varargs` method.
        A *varargs* method can accept a variable number of arguments.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toVarargs() {
        this.access |= Opcodes.ACC_VARARGS;
        return this;
    }

    @Info(
        """
        Remove the `varargs` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notVarargs() {
        this.access &= ~Opcodes.ACC_VARARGS;
        return this;
    }

    @Info(
        """
        @deprecated You cannot actually creates a `native` method as it requires native code implementation.

        Set the method to be a `native` method.
        A *native* method is implemented in native code using JNI.

        **Note:** Interface methods *cannot* set this flag.
            This flag *cannot* be set together with `abstract` flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toNative() {
        this.access |= Opcodes.ACC_NATIVE;
        return this;
    }

    @Info(
        """
        @deprecated You cannot actually creates a `native` method as it requires native code implementation.

        Remove the `native` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notNative() {
        this.access &= ~Opcodes.ACC_NATIVE;
        return this;
    }

    @Info(
        """
        Set the method to be an `abstract` method.
        An *abstract* method is a method that is declared without an implementation.

        **Note:** Interface methods *must* set this flag.
            This flag *cannot* be set together with `private`, `static`, `final`, `synchronized`, or `native` flags.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toAbstract() {
        this.access |= Opcodes.ACC_ABSTRACT;
        return this;
    }

    @Info(
        """
        Remove the `abstract` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notAbstract() {
        this.access &= ~Opcodes.ACC_ABSTRACT;
        return this;
    }

    @Info(
        """
        @deprecated This flag is unused in class file version 61 (Java 17) or above.

        Set the method to be a `strictfp` method.
        A *strictfp* method is a method that adheres to strict floating-point calculations.

        **Note:** This flag *cannot* be set together with `abstract` flag.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toStrictfp() {
        this.access |= Opcodes.ACC_STRICT;
        return this;
    }

    @Info(
        """
        @deprecated This flag is unused in class file version 61 (Java 17) or above.

        Remove the `strictfp` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notStrictfp() {
        this.access &= ~Opcodes.ACC_STRICT;
        return this;
    }

    @Info(
        """
        Set the method to be a `synthetic` method.
        A *synthetic* method is a method that is generated by the compiler and does not appear in the source code.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator toSynthetic() {
        this.access |= Opcodes.ACC_SYNTHETIC;
        return this;
    }

    @Info(
        """
        Remove the `synthetic` modifier from this method.

        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator notSynthetic() {
        this.access &= ~Opcodes.ACC_SYNTHETIC;
        return this;
    }

    @Info(
        """
        Specify the parameter names to use later in `ByteCodeBuilder`.

        By default, `arg0`, `arg1`, etc. are used to refer to method parameters.

        @param paramNames - The name of parameters. Must have the same length as the parameter types specified when creating this method.
        @returns This `MethodCreator` instance.
        """
    )
    public MethodCreator parameterNames(String[] paramNames) {
        this.paramNames = paramNames;
        return this;
    }

    @Info(
        """
        Begin byte code building.

        If you want to create *abstract* methods, use {@linkcode noCode}.

        @returns A `MethodCodeBuilder` for byte code building.  
            **Note:** After the `build()` method of the `MethodCodeBuilder` is called,
            The parent `ClassCreator` is returned directly.
            That means, once you have called this `code()` method, you should no longer access this `MethodCreator` again.
            Access modifier and other properties of this method should be set before calling this method.
        """
    )
    public MethodCodeBuilder code() {
        return new MethodCodeBuilder(this);
    }

    @Info(
        """
        Create a method without any code.
        This is used when creating abstract methods.

        **Note:** After calling this method, the parent `ClassCreator` is returned directly.
            That means, once you have called this `noCode()` method, you should no longer access this `MethodCreator` again.
            Access modifier and other properties of this method should be set before calling this method.

        @returns The parent `ClassCreator`.
        """
    )
    public ClassCreator noCode() {
        MethodVisitor mv = this.parent.classWriter.visitMethod(this.access, this.name, this.descriptor, null, null);
        mv.visitEnd();
        return this.parent;
    }

    public static class MethodCodeBuilder {

        private MethodCreator parent;

        private MethodVisitor methodVisitor;

        private ArrayList<String> localVariableNames = new ArrayList<>();
        private ArrayList<String> localVariableTypes = new ArrayList<>();

        public MethodCodeBuilder(MethodCreator parent) {
            this.parent = parent;
            this.methodVisitor = this.parent.parent.classWriter.visitMethod(this.parent.access, this.parent.name, this.parent.descriptor, null, null);
            this.methodVisitor.visitCode();

            String[] paramTypes = DescriptorUtils.fromMethodDescriptor(this.parent.descriptor);
            if ((this.parent.access & Opcodes.ACC_STATIC) == 0) {
                this.localVariableNames.add("this");
                this.localVariableTypes.add(DescriptorUtils.toFieldDescriptor(this.parent.parent.getClassName()));
            }

            String[] tempVarNames = this.parent.paramNames;
            if (tempVarNames == null) {
                tempVarNames = new String[paramTypes.length - 1];
                for (int i = 0; i < paramTypes.length - 1; i ++) {
                    tempVarNames[i] = "arg" + i;
                }
            } else if (tempVarNames.length != paramTypes.length - 1) {
                throw new IllegalArgumentException("Parameter names count does not match parameter types count");
            }

            for (int i = 0; i < paramTypes.length - 1; i ++) {
                String type = paramTypes[i];
                String name = tempVarNames[i];
                this.localVariableNames.add(name);
                this.localVariableTypes.add(type);
                if (type.equals("long") || type.equals("double")) {
                    this.localVariableNames.add(null);
                    this.localVariableTypes.add(null); // Dummy type for the wide slot
                }
            }
        }

        @Info(
            """
            Add a `nop` (no operation) instruction to the method.

            The `nop` instruction does nothing and is often used for alignment or timing purposes.

            **Operand Stack:**

            {...}  
            → {...}

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder noOperation() {
            this.methodVisitor.visitInsn(Opcodes.NOP);
            return this;
        }

        @Info(
            """
            Add a `aconst_null` instruction to the method.

            The `aconst_null` instruction pushes a `null` reference onto the operand stack.

            **Operand Stack:**

            { ... }  
            → { ... , `null` }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pushNull() {
            this.methodVisitor.visitInsn(Opcodes.ACONST_NULL);
            return this;
        }

        @Info(
            """
            Add an instruction to push an integer constant onto the operand stack.

            The method optimizes the instruction based on the value of the integer:
            - For values between -1 and 5 (inclusive), it uses the `ICONST_<i>` instructions.
            - For values between -128 and 127 (inclusive), it uses the `BIPUSH` instruction.
            - For values between -32,768 and 32,767 (inclusive), it uses the `SIPUSH` instruction.
            - For all other values, it uses the `LDC` instruction.

            **Operand Stack:** (*i* is the pushed integer constant.)

            { ... }  
            → { ... , *i* }

            @param i - The integer constant to push onto the operand stack.
            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pushInt(int i) {
            if (i >= -1 && i <= 5) {
                this.methodVisitor.visitInsn(Opcodes.ICONST_0 + i);
            } else if (i >= Byte.MIN_VALUE && i <= Byte.MAX_VALUE) {
                this.methodVisitor.visitIntInsn(Opcodes.BIPUSH, i);
            } else if (i >= Short.MIN_VALUE && i <= Short.MAX_VALUE) {
                this.methodVisitor.visitIntInsn(Opcodes.SIPUSH, i);
            } else {
                this.methodVisitor.visitLdcInsn(i);
            }
            return this;
        }

        @Info(
            """
            Add an instruction to push a long constant onto the operand stack.

            The method optimizes the instruction based on the value of the long:
            - For values 0L and 1L, it uses the `LCONST_0` and `LCONST_1` instructions respectively.
            - For all other values, it uses the `LDC` instruction.

            **Operand Stack:** (*l* is the pushed long constant. "---" is the second slot taken by the long.)

            { ... }  
            → { ... , *l* , --- }

            @param l - The long constant to push onto the operand stack.
            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pushLong(long l) {
            if (l == 0L) {
                this.methodVisitor.visitInsn(Opcodes.LCONST_0);
            } else if (l == 1L) {
                this.methodVisitor.visitInsn(Opcodes.LCONST_1);
            } else {
                this.methodVisitor.visitLdcInsn(l);
            }
            return this;
        }

        @Info(
            """
            Add an instruction to push a float constant onto the operand stack.

            The method optimizes the instruction based on the value of the float:
            - For values 0.0f, 1.0f, and 2.0f, it uses the `FCONST_0`, `FCONST_1`, and `FCONST_2` instructions respectively.
            - For all other values, it uses the `LDC` instruction.

            **Operand Stack:** (*f* is the pushed float constant.)

            { ... }  
            → { ... , *f* }

            @param f - The float constant to push onto the operand stack.
            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pushFloat(float f) {
            if (f == 0.0f) {
                this.methodVisitor.visitInsn(Opcodes.FCONST_0);
            } else if (f == 1.0f) {
                this.methodVisitor.visitInsn(Opcodes.FCONST_1);
            } else if (f == 2.0f) {
                this.methodVisitor.visitInsn(Opcodes.FCONST_2);
            } else {
                this.methodVisitor.visitLdcInsn(f);
            }
            return this;
        }

        @Info(
            """
            Add an instruction to push a double constant onto the operand stack.

            The method optimizes the instruction based on the value of the double:
            - For values 0.0 and 1.0, it uses the `DCONST_0` and `DCONST_1` instructions respectively.
            - For all other values, it uses the `LDC` instruction.

            **Operand Stack:** (*d* is the pushed double constant. "---" is the second slot taken by the double.)

            { ... }  
            → { ... , *d* , --- }

            @param d - The double constant to push onto the operand stack.
            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pushDouble(double d) {
            if (d == 0.0) {
                this.methodVisitor.visitInsn(Opcodes.DCONST_0);
            } else if (d == 1.0) {
                this.methodVisitor.visitInsn(Opcodes.DCONST_1);
            } else {
                this.methodVisitor.visitLdcInsn(d);
            }
            return this;
        }

        @Info(
            """
            Add an instruction to push a string constant onto the operand stack.

            The method uses the `LDC` instruction to push the string.

            **Operand Stack:** (*s* is the pushed string constant.)

            { ... }  
            → { ... , *s* }

            @param s - The string constant to push onto the operand stack.
            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pushString(String s) {
            this.methodVisitor.visitLdcInsn(s);
            return this;
        }

        private int getVariableIndexOrThrow(String variableName, String requiredType) {
            int result = getVariableIndexOrThrow(variableName);
            if (this.localVariableTypes.get(result).equals(requiredType)) return result;
            throw new IllegalArgumentException("Local variable '" + variableName + "' is not of type '" + requiredType + "', but a '" +
                this.localVariableTypes.get(result) +"'.");
        }

        private int getVariableIndexOrThrow(String variableName) {
            int index = this.localVariableNames.indexOf(variableName);
            if (index == -1) {
                throw new IllegalArgumentException("Local variable '" + variableName + "' does not exist.");
            }
            return index;
        }

        private int getVariableIndexOrDeclare(String variableName, String requiredType) {
            if (requiredType == "long" || requiredType == "double") {
                throw new IllegalArgumentException("Use getVariableIndexOrDeclareWide for long and double types.");
            }
            int index = this.localVariableNames.indexOf(variableName);
            if (index == -1) {
                this.localVariableNames.add(variableName);
                this.localVariableTypes.add(requiredType);
                index = this.localVariableNames.size() - 1;
            } else {
                String original = this.localVariableTypes.get(index);
                if (original == "long" || original == "double") {
                    throw new IllegalArgumentException("Local variable '" + variableName + "' is of wide type '" + original + "'.");
                }
                this.localVariableTypes.set(index, requiredType);
            }
            return index;
        }

        // Push a null to the second slot of the wide variable into the variable table
        private int getVariableIndexOrDeclareWide(String variableName, String requiredType) {
            if (!requiredType.equals("long") && !requiredType.equals("double")) {
                throw new IllegalArgumentException("Only long and double is allowed, but received " + requiredType);
            }
            int index = this.localVariableNames.indexOf(variableName);
            if (index == -1) {
                this.localVariableNames.add(variableName);
                this.localVariableTypes.add(requiredType);
                this.localVariableNames.add(null);
                this.localVariableTypes.add(null); // Dummy type for the wide slot
                index = this.localVariableNames.size() - 2;
            } else {
                String original = this.localVariableTypes.get(index);
                if (original != "long" && original != "double") {
                    throw new IllegalArgumentException("Local variable '" + variableName + "' is not of wide type '" + original + "'.");
                }
                this.localVariableTypes.set(index, requiredType);
            }
            return index;
        }

        @Info(
            """
            Add an `iload` instruction to the method.

            The `iload` instruction loads an integer from a local variable onto the operand stack.

            **Operand Stack:** (*i* is the loaded integer.)

            { ... }  
            → { ... , *i* }

            @param variableName - The name of the local variable to load the integer from.
                Use `this` for instance methods to refer to the current object (if this method is an instance method).
                Parameters names are `arg0`, `arg1`, etc. at default.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable does not exist or is not of type `int`.
            """
        )
        public MethodCodeBuilder loadInt(String variableName) {
            int index = this.getVariableIndexOrThrow(variableName, "int");
            this.methodVisitor.visitVarInsn(Opcodes.ILOAD, index);
            return this;
        }

        @Info(
            """
            Add an `lload` instruction to the method.

            The `lload` instruction loads a long from a local variable onto the operand stack.

            **Operand Stack:** (*l* is the loaded long and "---" is the second slot taken.)

            { ... }  
            → { ... , *l* , --- }

            @param variableName - The name of the local variable to load the long from.
                Use `this` for instance methods to refer to the current object (if this method is an instance method).
                Parameters names are `arg0`, `arg1`, etc. at default.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable does not exist or is not of type `long`.
            """
        )
        public MethodCodeBuilder loadLong(String variableName) {
            int index = this.getVariableIndexOrThrow(variableName, "long");
            this.methodVisitor.visitVarInsn(Opcodes.LLOAD, index);
            return this;
        }

        @Info(
            """
            Add an `fload` instruction to the method.

            The `fload` instruction loads a float from a local variable onto the operand stack.

            **Operand Stack:** (*f* is the loaded float.)

            { ... }  
            → { ... , *f* }

            @param variableName - The name of the local variable to load the float from.
                Use `this` for instance methods to refer to the current object (if this method is an instance method).
                Parameters names are `arg0`, `arg1`, etc. at default.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable does not exist or is not of type `float`.
            """
        )
        public MethodCodeBuilder loadFloat(String variableName) {
            int index = this.getVariableIndexOrThrow(variableName, "float");
            this.methodVisitor.visitVarInsn(Opcodes.FLOAD, index);
            return this;
        }

        @Info(
            """
            Add an `dload` instruction to the method.

            The `dload` instruction loads a double from a local variable onto the operand stack.

            **Operand Stack:** (*d* is the loaded double and "---" is the second slot taken.)

            { ... }  
            → { ... , *d* , --- }

            @param variableName - The name of the local variable to load the double from.
                Use `this` for instance methods to refer to the current object (if this method is an instance method).
                Parameters names are `arg0`, `arg1`, etc. at default.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable does not exist or is not of type `double`.
            """
        )
        public MethodCodeBuilder loadDouble(String variableName) {
            int index = this.getVariableIndexOrThrow(variableName, "double");
            this.methodVisitor.visitVarInsn(Opcodes.DLOAD, index);
            return this;
        }

        @Info(
            """
            Add an `aload` instruction to the method.

            The `aload` instruction loads an object reference from a local variable onto the operand stack.

            **Operand Stack:** (*object* is the loaded object reference.)

            { ... }  
            → { ... , *object* }

            @param variableName - The name of the local variable to load the object from.
                Use `this` for instance methods to refer to the current object (if this method is an instance method).
                Parameters names are `arg0`, `arg1`, etc. at default.
            @param requiredType - The class name of the object.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable does not exist or is not of the required type.
            """
        )
        public MethodCodeBuilder loadObject(String variableName, String requiredType) {
            int index = this.getVariableIndexOrThrow(variableName, requiredType);
            this.methodVisitor.visitVarInsn(Opcodes.ALOAD, index);
            return this;
        }

        @Info(
            """
            Add an `aload` instruction to the method. And do not check whether the type is valid.

            The `aload` instruction loads an object reference from a local variable onto the operand stack.

            **Operand Stack:** (*object* is the loaded object reference.)

            { ... }  
            → { ... , *object* }

            @param variableName - The name of the local variable to load the object from.
                Use `this` for instance methods to refer to the current object (if this method is an instance method).
                Parameters names are `arg0`, `arg1`, etc. at default.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable does not exist or is not of an object type.)
            """
        )
        public MethodCodeBuilder loadObject(String variableName) {
            int index = this.getVariableIndexOrThrow(variableName);
            this.methodVisitor.visitVarInsn(Opcodes.ALOAD, index);
            return this;
        }

        @Info(
            """
            Add an `istore` instruction to the method.

            The `istore` instruction stores an integer from the operand stack into a local variable.

            **Note:** All *store* instructions *overrides* the variable type.

            **Operand Stack:** (*i* is the stored integer.)

            { ... , *i* }  
            → { ... }

            @param variableName - The name of the local variable to store the integer into.
                Use `this` for instance methods to refer to the current object (if this method is an instance method).
                Parameters names are `arg0`, `arg1`, etc. at default. (Change them using `parameterNames(String[])` method before calling `code()`.)
                If the local variable does not exist, it will be created.
            @returns This `MethodCodeBuilder` instance.
            @throws `IllegalArgumentException` - if the local variable exists but is not of type `int`.
            """
        )
        public MethodCodeBuilder storeInt(String variableName) {
            int index = this.getVariableIndexOrDeclare(variableName, "int");
            this.methodVisitor.visitVarInsn(Opcodes.ISTORE, index);
            return this;
        }

        @Info(
            """
            Add an `lstore` instruction to the method.

            The `lstore` instruction stores a long from the operand stack into a local variable.

            **Note:** All *store* instructions *overrides* the variable type.

            **Operand Stack:** (*l* is the stored long and "---" is the second slot taken.)

            { ... , *l* , --- }  
            → { ... }

            @param variableName - The name of the local variable to store the long into.
                If the local variable does not exist, it will be created.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable exists but is not of type `long`.
            """
        )
        public MethodCodeBuilder storeLong(String variableName) {
            int index = this.getVariableIndexOrDeclareWide(variableName, "long");
            this.methodVisitor.visitVarInsn(Opcodes.LSTORE, index);
            return this;
        }

        @Info(
            """
            Add an `fstore` instruction to the method.

            The `fstore` instruction stores a float from the operand stack into a local variable.

            **Note:** All *store* instructions *overrides* the variable type.

            **Operand Stack:** (*f* is the stored float.)

            { ... , *f* }  
            → { ... }

            @param variableName - The name of the local variable to store the float into.
                If the local variable does not exist, it will be created.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable exists but is not of type `float`.
            """
        )
        public MethodCodeBuilder storeFloat(String variableName) {
            int index = this.getVariableIndexOrDeclare(variableName, "float");
            this.methodVisitor.visitVarInsn(Opcodes.FSTORE, index);
            return this;
        }

        @Info(
            """
            Add an `dstore` instruction to the method.

            The `dstore` instruction stores a double from the operand stack into a local variable.

            **Note:** All *store* instructions *overrides* the variable type.

            **Operand Stack:** (*d* is the stored double and "---" is the second slot taken.)

            { ... , *d* , --- }  
            → { ... }

            @param variableName - The name of the local variable to store the double into.
                If the local variable does not exist, it will be created.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable exists but is not of type `double`.
            """
        )
        public MethodCodeBuilder storeDouble(String variableName) {
            int index = this.getVariableIndexOrDeclareWide(variableName, "double");
            this.methodVisitor.visitVarInsn(Opcodes.DSTORE, index);
            return this;
        }

        @Info(
            """
            Add an `astore` instruction to the method.

            The `astore` instruction stores an object reference from the operand stack into a local variable.

            **Note:** All *store* instructions *overrides* the variable type.

            **Operand Stack:** (*object* is the stored object reference.)

            { ... , *object* }  
            → { ... }

            @param variableName - The name of the local variable to store the object into.
            @param variableType - The class name of the object stored.
            @returns This `MethodCodeBuilder` instance.
            @throws IllegalArgumentException if the local variable exists but is not of an object type.
            """
        )
        public MethodCodeBuilder storeObject(String variableName, String variableType) {
            int index = this.getVariableIndexOrDeclare(variableName, variableType);
            this.methodVisitor.visitVarInsn(Opcodes.ASTORE, index);
            return this;
        }

        @Info(
            """
            Add a `pop` instruction to the method.

            The `pop` instruction removes the top value from the operand stack.

            **Note:** This instruction can only be used to pop values that take up one slot (e.g., int, float, reference).
                For removing longs and doubles, use the `pop2` instruction instead.

            **Operand Stack:** (*v* is the popped value.)

            { ... , *v* }  
            → { ... }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pop() {
            this.methodVisitor.visitInsn(Opcodes.POP);
            return this;
        }

        @Info(
            """
            Add a `pop2` instruction to the method.

            The `pop2` instruction removes the top one or two values from the operand stack.

            **Operand Stack:**

            - If the top value is a long or double: (*v1* is the popped long or double, and "---" is the second slot taken.)  
              { ... , *v1* , --- }  
              → { ... }

            - Otherwise: (*v1* and *v2* are the popped values and neither of them is a long or a double.)  
              { ... , *v2* , *v1* }  
              → { ... }

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder pop2() {
            this.methodVisitor.visitInsn(Opcodes.POP2);
            return this;
        }

        @Info(
            """
            Add a `ireturn` instruction to the method.

            The `ireturn` instruction is used to return an integer from a method.
            Before `ireturn`, the operand stack must have ***one and only one*** integer value.

            **Operand Stack:** (*i* is the returned integer.)

            { *i* }  
            → [*EMPTY*]

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder returnInt() {
            this.methodVisitor.visitInsn(Opcodes.IRETURN);
            return this;
        }

        @Info(
            """
            Add a `lreturn` instruction to the method.

            The `lreturn` instruction is used to return a long from a method.
            Before `lreturn`, the operand stack must have ***one and only one*** long value (which takes two slots).

            **Operand Stack:** (*l* is the returned long. "---" is the second slot taken by the long.)

            { *l* , --- }  
            → [*EMPTY*]

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder returnLong() {
            this.methodVisitor.visitInsn(Opcodes.LRETURN);
            return this;
        }

        @Info(
            """
            Add a `freturn` instruction to the method.

            The `freturn` instruction is used to return a float from a method.
            Before `freturn`, the operand stack must have ***one and only one*** float value.

            **Operand Stack:** (*f* is the returned float.)

            { *f* }  
            → [*EMPTY*]

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder returnFloat() {
            this.methodVisitor.visitInsn(Opcodes.FRETURN);
            return this;
        }

        @Info(
            """
            Add a `dreturn` instruction to the method.

            The `dreturn` instruction is used to return a double from a method.
            Before `dreturn`, the operand stack must have ***one and only one*** double value (which takes two slots).

            **Operand Stack:** (*d* is the returned double. "---" is the second slot taken by the double.)

            { *d* , --- }  
            → [*EMPTY*]

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder returnDouble() {
            this.methodVisitor.visitInsn(Opcodes.DRETURN);
            return this;
        }

        @Info(
            """
            Add an `areturn` instruction to the method.

            The `areturn` instruction is used to return a reference from a method.
            Before `areturn`, the operand stack must have ***one and only one*** reference value.

            **Operand Stack:** (*o* is the returned reference.)

            { *o* }  
            → [*EMPTY*]

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder returnObject() {
            this.methodVisitor.visitInsn(Opcodes.ARETURN);
            return this;
        }

        @Info(
            """
            Add a `return` instruction to the method.

            The `return` instruction is used to return from a method that has a `void` return type.
            Before `return`, the operand stack must be ***empty***.

            **Operand Stack:**

            [*EMPTY*]  
            → [*EMPTY*]

            @returns This `MethodCodeBuilder` instance.
            """
        )
        public MethodCodeBuilder returnVoid() {
            this.methodVisitor.visitInsn(Opcodes.RETURN);
            return this;
        }

        @Info(
            """
            Ends the method creation and returns to the parent `ClassCreator`.

            **Note:** Do not try to add any codes after this method.
            They may cause undefined behaviors.

            @returns The parent `ClassCreator`.  
                **Note**: The returned is ***NOT*** the parent `MethodCreator`, but the `ClassCreator`.
            """
        )
        public ClassCreator build() {
            methodVisitor.visitMaxs(0, 0);
            methodVisitor.visitEnd();
            return this.parent.parent;
        }

    }

}
